# Keyboard Name
CONFIG_ZMK_KEYBOARD_NAME="Corne RP"

# Display
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_WIDGET_BATTERY_STATUS_SHOW_PERCENTAGE=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_BUILT_IN=y
CONFIG_ZMK_DISPLAY_BLANK_ON_IDLE=y

# Slow LVGL refresh
CONFIG_ZMK_DISPLAY_TICK_PERIOD_MS=100

# Power & Sleep
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_TIMEOUT=10000
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=300000

# LED control
CONFIG_ZMK_RGB_UNDERGLOW=n
CONFIG_ZMK_BACKLIGHT=n

# Bluetooth — balanced latency vs power
CONFIG_BT_GAP_PERIPHERAL_PREF_PARAMS=y
CONFIG_BT_PERIPHERAL_PREF_MIN_INT=24
CONFIG_BT_PERIPHERAL_PREF_MAX_INT=40
